source "https://rubygems.org"

ruby File.read(File.expand_path("../../.ruby-version", __dir__)).strip rescue nil

gem "sinatra", "~> 3.2"
gem "rackup", "~> 2.1"

group :test do
  gem "rspec", "~> 3.13"
  gem "rack-test", "~> 2.1"
end

